### ISSUE TITLE
Ibytes / Obytes limited to 8 bytes ?

### ISSUE THREAD

**Issue by lionel590** [Cloud-Automation/node-soem#11]
Hi Stefan, is there any reason why you limit Ibytes, same applies to Obytes, to 8 bytes ? shouldn't we just make sure that num bytes reported by slave matches the bits ? 
```
numbytes = ec_slave[i].Ibytes;
if ((numbytes == 0) && (ec_slave[i].Ibits > 0)) numbytes = 1;
if (numbytes > 8) numbytes = 8;

```
Rgds

**Comment by stefanpoeter** [comment]
Ohh, this is an old project and no longer supported :-) Feel free to fork and use it :-)
