### ISSUE TITLE
npm fails on Ubuntu 16.04LTS 32bit at "node-gyp rebuild" 

### ISSUE THREAD

**Issue by gicho** [Cloud-Automation/node-soem#4]
Attempt to "sudo npm install node-soem" fails at "node-gyp rebuild".
Node.js is "v4.2.6". Also installed "nodejs-legacy" but no change.
SOEM was installed before this and seems to work fine.

Additional info - the first error is on building "../src/node-sooem-master.cc:8:22: fatal error: ethercat.h: No such file or directory". I will try to find why.

**Comment by jonwooding** [comment]
I had the same issue months ago. If I remember correctly it was a Node version issue, but I could be completely wrong about that. I'll try to look in to it to see if I can remember what the problem was. Good luck!

**Comment by stefanpoeter** [comment]
Any progress?

**Comment by stefanpoeter** [comment]
Since there is not much happening here I'll close this issue. Have a look at version 0.1.5 for changes.
